### ISSUE TITLE
Multiple unit options are possible for parameter 'base peak intensity' but none were specified

### ISSUE THREAD

**Issue by mafreitas** [mobiusklein/psims#11]
We are using psims to create mzml from tdf files using the bruker sdk.  When assigning units to base peak intensity I get the following warning.

/usr/local/lib/python3.8/dist-packages/psims/mzml/components.py:585: AmbiguousTermWarning: Multiple unit options are possible for parameter 'base peak intensity' but none were specified
  self._check_params()

/usr/local/lib/python3.8/dist-packages/psims/mzml/components.py:614: AmbiguousTermWarning: Multiple unit options are possible for parameter 'base peak intensity' but none were specified
  self.write_params(xml_file)

The code section to assign the unit is below.

```
    mzml_data_struct['writer'].write_spectrum(
        ms1_mz_array, 
        ms1_i_array, 
        id=mzml_data_struct['current_precursor']['spectrum_id'], 
        centroided=centroided_flag,
        scan_start_time=scan_start_time, 
        scan_window_list=[( mzml_data_struct['data_dict']['mz_acq_range_lower'] , mzml_data_struct['data_dict']['mz_acq_range_upper'] )],
        compression=mzml_data_struct['compression'],
        params=[
                {"ms level": 1}, 
                {"total ion current": total_ion_intensity},
                {"base peak intensity": base_peak_intensity, 'unit_accession': 'MS:1000131'},
                {"base peak m/z": base_peak_mz, 'unit_name': 'm/z'}
            ]
        )
```

**Comment by mobiusklein** [comment]
Thank you for reporting this issue. Problem appears to be that parameters which are specified in compact notation `{name: value}` were not having their units extracted properly.

This should be fixed in cb869077405e303294c7ea0faea9bf1bb1ed3bb1. Can you give that commit a try please?

**Comment by mafreitas** [comment]
Worked like a charm!  Will this be available in pip?  We install psims inside a docker container as a dependency with our script.

**Comment by mafreitas** [comment]
Also should note, this commit also fixed a separate issue where units were not being associated with the corresponding PSI-MS unit.  I was going to include a separate issue, but appears to be fixed now.

**Comment by mobiusklein** [comment]
I can do a formal release later today, but probably not in the next four hours.

**Comment by mobiusklein** [comment]
Fix is live on https://pypi.org/project/psims/0.1.31/

**Comment by mobiusklein** [comment]
@mafreitas please let me know if I've fixed the problem so we can close this issue

Thank you.

**Comment by mafreitas** [comment]
Appears to be working. Thank you.
