### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by RalfG** [mobiusklein/psims#13]
Hi @mobiusklein,

While setting up a new conda environment, I noticed psims is not in bioconda yet. If you want, I can take a look at drafting a bioconda recipe and some GitHub action workflows for automated testing, building and uploading to PyPI etc.

Let me know what you think,
Ralf

**Comment by mobiusklein** [comment]
I currently don't use `conda` as a package index, but if you'd like to either point me to the documentation or create a GitHub action to build and publish there, I'd be happy to add it.

I currently do CI testing and PyPI tag publishing on GitHub actions. Was there something else I was missing beyond a conda recipe?

**Comment by RalfG** [comment]
Docs for bioconda building are here: https://bioconda.github.io/contributor/index.html
Should be pretty straight for a pure Python package. In short, you add a yaml file to the bioconda repo, which will initiate building and testing on their CI, and the package is updated automatically each time a new PyPI release is available. 

I'll have some free time to look at this in two weeks, but of course feel free to get started if you want.

Sorry, I seem to have missed those... 🤦Looks good!

**Comment by RalfG** [comment]
`psims` has been added to bioconda:
- PR: https://github.com/bioconda/bioconda-recipes/pull/32721
- Web page: https://anaconda.org/bioconda/psims

On each PyPI update, the bioconda package will be updated automatically as well. The bioconda recipe only needs manual updating when dependencies have changed.
