### ISSUE TITLE
Files not closing (was: Truncated files)

### ISSUE THREAD

**Issue by bkalafut1** [mobiusklein/psims#16]
Files are being  truncated in the middle or the end of the final spectrum, without the index being written.  Sporadically, everything works but it is not typically so.

A copy and paste is not displaying properly.  I will attach an example shortly.

**Comment by bkalafut1** [comment]
[smallMolecule-30eV-1.zip](https://github.com/mobiusklein/psims/files/8912463/smallMolecule-30eV-1.zip)

**Comment by mobiusklein** [comment]
Are you using the `MzMLWriter` as a context manager or explicitly calling it's `close` method?

**Comment by bkalafut1** [comment]
As a context manager, pasted below.
It seems that the file is not being released, either, but I've confirmed by insertion of prints that each of the with blocks exits.

`def write_spectra(filename,description,spectrum_iterable,*,count=0): #count=0 appears to create a valid file
    with MzMLWriter(filename) as writer: #Context manager takes care of begin and the like
        writer.controlled_vocabularies()
        writer.file_description([description])
        #writer.scan_settings_list([])
        writer.software_list([{"id":"psims-writer","version":"0.1.2","params":["python-psims"]},
                              {"id":"automaf","version":"0.0000001"}])
                              
        source=writer.Source(1,["electrospray ionization", "electrospray inlet"])
        analyzer=writer.Analyzer(2,["IMS","TOF"])
        detector=writer.Detector(3,["conversion dynode electron multiplier"])
        config=writer.InstrumentConfiguration(id="IC1",component_list=[source,analyzer,detector])
        writer.instrument_configuration_list([config])
        writer.data_processing_list([writer.DataProcessing([writer.ProcessingMethod(order=1,software_reference="automaf")],id=1,)]) #This is very specific to prototyping and woudl need to be changed for a general case.
        with writer.run(id=1):
            with writer.spectrum_list(count):
                for spectrum,index in zip(spectrum_iterable,itertools.count()):
                    spectrum.mzML_write_spectrum(writer,index)`

**Comment by bkalafut1** [comment]
That cut and paste isn't showing; I've attached another Zip
[mzMLSupport.zip](https://github.com/mobiusklein/psims/files/8912539/mzMLSupport.zip)
p

**Comment by bkalafut1** [comment]
Going through the source code, it looks like the __exit__ method doesn't close the file unless the writer object has a "close" attribute set.  The entire file does get written if this happens.  Is this as-designed?

**Comment by mobiusklein** [comment]
It looks like some tortured logic that I have since ceased to notice because it worked in my use cases and my tests always passed `close=True`. I'm going factor that feature out so that it always closes the file by default unless you specifically ask for it not to. In the mean time, pass `close=True` when you create `MzMLWriter` instances.

**Comment by mobiusklein** [comment]
I've released v1.0.0 on PyPI (https://pypi.org/project/psims/) which should have the expected behavior.

**Comment by bkalafut1** [comment]
Yes, this works—thank you very much!
