### ISSUE TITLE
[Maintainance] Deprecation warnings for sqlalchemy 2.0

### ISSUE THREAD

**Issue by jspaezp** [mobiusklein/psims#18]
I noticed that the current implementation is trowing deprecation warning due to sqlalchemy.

```
... site-packages/psims/controlled_vocabulary/unimod.py:49: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base(metaclass=SubclassRegisteringDeclarativeMeta)
```

LMK if you would like any help with a PR that starts using the new API

**Comment by mobiusklein** [comment]
I've updated the import for `declarative_base` and `DeclarativeMeta`. Do you see any other warnings?

**Comment by jspaezp** [comment]
Not that I recall at this time! Let me know of the commit or the branch that would have the change if you want me to test it out :) thanks a lot!

**Comment by mobiusklein** [comment]
It's on master at 57772a21117a9dec34b283b8b8a54e50e0adb786. My assessment was that if it passed the unit tests it was safe to use the latest SQLAlchemy.

I have another, much larger SQLAlchemy using project I'll have to check on for compatibility.

**Comment by jspaezp** [comment]
It seems like all warnings are gone on that branch!
Thank you very much!
just FYI i think it would be good if you left a comment in the try-except mentioning that this is to support sqlalchemy 1.xx and 2.xx :) future contributors will appreciate that.

**Comment by mobiusklein** [comment]
Thank you for checking. I added the comment for the future. This version was tagged at v1.2.4 and should be live on PyPI soon.
