### ISSUE TITLE
Binary string in IndexedMzML?

### ISSUE THREAD

**Issue by bretttully** [mobiusklein/psims#5]
The index id doesn't match the spectrum id, possibly due to py3 binary string issues?
Spectrum id:
```
<spectrum index="0" defaultArrayLength="0" id="sample=0 period=0 cycle=0 experiment=0">
```
Offset id:
```
<offset idRef="b'sample=0 period=0 cycle=0 experiment=0'">2729</offset>
```

This then causes massive slow-down when parsing the file using `mzml.PreIndexedMzML` (3 orders of magnitude).

**Expected**:
Offset id shouldn't have `b''` wrapping it. E.g.:
```
<offset idRef="sample=0 period=0 cycle=0 experiment=0">2729</offset>
```

**Comment by mobiusklein** [comment]
Yes, that appears to be what happened. When the various `IndexedXML` implementations in `pyteomics` fail to find the ID in the index, they fall back to sequential lookup. I think this should be reasonably simple to fix within the day.

**Comment by mobiusklein** [comment]
Could you please check that you're getting the desired behavior with the most recent tag, [v0.1.26](https://github.com/mobiusklein/psims/releases/tag/v0.1.26)? I'll be cutting a PyPI release shortly.

**Comment by bretttully** [comment]
That has fixed it, thank you for such a quick turn-around!!

**Comment by mobiusklein** [comment]
Thank you for using my work. I'll leave this issue open for a few days in case a problem arises from the fix. Otherwise, feel free to close it if you feel the issue is resolved.

**Comment by bretttully** [comment]
Have tested on a number of files now and all is well. Closing.
