### ISSUE TITLE
Recommended usage pattern for extracting & saving just header info from mzML

### ISSUE THREAD

**Issue by bretttully** [mobiusklein/psims#6]
If I have an mzML file and I wish to use pyteomics (to load) & psims (to write out) is there a suggested usage pattern to achieve the following:

1. Load mzML file
2. Extract just the header/metadata (i.e. exclude spectra and chromatograms)
3. Save this header/metadata to a new mzML file

(Not sure if this is the best place to ask).

**Comment by mobiusklein** [comment]
That this question doesn't have an answer is a "documentation issue", one of the greatest weaknesses of software written by graduate students, especially when this is not a grant goal.

You could use the `MzMLTransformer` as a template. Do you manipulate the metadata at all en route to the new file?

If not, you could just directly use `MzMLTransformer`:
```python
from psims.transform.mzml import MzMLTransformer

with open("metadata.mzML", 'wb') as out:
    trans = MzMLTransformer("full.mzML", out)
    with trans.writer:
        trans.writer.controlled_vocabularies()
        trans.copy_metadata()
```
`MzMLTransformer.copy_metadata` will copy `fileDescription`, `softwareList`, `referenceableParamGroupList`, `instrumentConfigurationList`, and `dataProcessingList`. I haven't seen any examples with `sampleList` or `scanSettingsList` so I couldn't include them in the copying process.

**Comment by bretttully** [comment]
That is excellent, thank you!
